DATASET_DIR_PATH = 'dataset/'
TRAIN_DATASET_DIR_PATH = DATASET_DIR_PATH + 'train/'
VAL_DATASET_DIR_PATH = DATASET_DIR_PATH + 'val/'
MODEL_FILES_DIR_PATH = 'model_files/'
MODEL_JOBLIB_PATH = MODEL_FILES_DIR_PATH + 'model.joblib'
LABEL_ENCODER_JOBLIB_PATH = MODEL_FILES_DIR_PATH + 'label_encoder.joblib'
MODEL_METRICS_PATH = MODEL_FILES_DIR_PATH + 'metrics.txt'

IMG_SIZE = (160, 160)
FACENET_MODEL_KEY = '20170511-185253'